### ISSUE TITLE
SSLV3 handshake failure

### ISSUE THREAD

**Issue by uniway** [maplecool/easytrojan#11]
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

更新了curl还是出错，请大神看一下是哪里没设置好吗？

**Comment by itrilogy** [comment]
我也遇见一样的问题。请问你是怎么解决的呢？

**Comment by uniway** [comment]
> 我也遇见一样的问题。请问你是怎么解决的呢？

没解决，安装中断。你解决了吗

**Comment by maplecool** [comment]
请参考 https://github.com/maplecool/easytrojan/issues/7
