### ISSUE TITLE
我的ip端口443被阻断了

### ISSUE THREAD

**Issue by AbianTang** [maplecool/easytrojan#14]
sed -i "s/443/8443/g" /etc/caddy/Caddyfile && systemctl restart caddy.service 正常使用 443无法使用

**Comment by maplecool** [comment]
The problem with using port 443 for this project is caused by client problems. 
You need to check whether the client you need to test is configured correctly according to the project instructions.

**Comment by AbianTang** [comment]
> 本项目使用443端口出现问题是客户端问题导致的。 您需要检查您需要测试的客户端是否按照项目说明配置正确。

你好，谢谢你的恢复，经过我自行配置trojan测试核实确定了443被阻断了，其他端口是正常的。

 sudo systemctl status trojan.service
● trojan.service - Trojan Service
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: active (running) since 六 2023-03-25 05:45:24 EDT; 8s ago
 Main PID: 3770 (trojan)
   CGroup: /system.slice/trojan.service
           └─3770 /root/trojan/trojan -c /root/trojan/config.json
