### ISSUE TITLE
有没有兴趣加ipv6的优化

### ISSUE THREAD

**Issue by Potterli20** [maplecool/easytrojan#2]
有没有兴趣加ipv6的优化？

**Comment by maplecool** [comment]
我不在大陆，没有境内ipv6的测试环境，暂时无法实现，欢迎PR : D

**Comment by maplecool** [comment]
> > 我不在大陆，没有境内ipv6的测试环境，暂时无法实现，欢迎PR : D
> 
> 国外不是也有？

没有GFW影响的网络环境，没法作为该项目的测试标准，如果急切需ipv6，可以使用当前脚本部署成功后，自行修改/etc/caddy目录下的配置文件，将ipv4改成ipv6
