### ISSUE TITLE
Is EasyTrojan available for multiple users? 

### ISSUE THREAD

**Issue by mshigemoto** [maplecool/easytrojan#5]
Is EasyTrojan available for multiple users?
If so, how do I set multiple users and passwords?
Thank you before.

**Comment by maplecool** [comment]
easytrojan has no users and only passwords, please execute the file mytrojan.sh to add multiple passwords

**Comment by mshigemoto** [comment]
Dear maplecool
Thank you very much for your replay. I understood.
