### ISSUE TITLE
流量统计可用增加显示单位吗

### ISSUE THREAD

**Issue by BrunuhVille** [maplecool/easytrojan#6]
大佬您好
data usage: {"up":1393344,"down":123816228}
希望流量统计可以增加显示单位例如mb、gb

**Comment by maplecool** [comment]
请向caddy的trojan插件原作者反馈，脚本只是用来自动化部署，没有做任何程序上的处理

**Comment by Edcwsyh** [comment]
可以简单封装一下密码脚本, 会打印所有密码并转化为MB单位
`./mytrojan.sh status $(./mytrojan.sh list) | awk -F'[:,]' '{up=$3/1024/1024; down=$5/1024/1024; printf "%s : {\"up\":%.2f MB,\"down\":%.2f MB}\n", $1, up, down}'`
