### ISSUE TITLE
证书申请通过不了

### ISSUE THREAD

**Issue by Chnancheek** [maplecool/easytrojan#7]
用了三台服务器，两台都获取不了证书，ufw放行和关闭都试了，系统也换了，可以排查一下证书获取吗

**Comment by Chnancheek** [comment]
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by maplecool** [comment]
如果确定防火墙与网络没问题，请尝试使用自己的域名，或等半小时后重新安装
