### ISSUE TITLE
某个时间点后，安装存在问题

### ISSUE THREAD

**Issue by shenzhui007** [maplecool/easytrojan#9]
系统：Debian, 已开启80&443端口

问题描述：2月初的时候能顺利安装的，现在在新机子上安装的时候卡在以下这步没反应：

requesting build        {"os": "linux", "arch": "amd64", "packages": ["github.com/imgk/caddy-trojan@8d46fda7c33580ed047d557fc97b512a42ec398b"]}

**Comment by fgprodigal** [comment]
是的，同样这个问题，add-package卡住，试了个别的package没问题，不知道咋回事，最后我把别的vps的caddy搞过来用了

**Comment by fgprodigal** [comment]
今天又好了😂

**Comment by maplecool** [comment]
貌似是caddy的在线编译出了问题，看起来官方已经修复了
